<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Total_JumlahData</name>
   <tag></tag>
   <elementGuidId>1c792eb3-e1b0-43ca-8bc2-40e92254a8eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#example1_info</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='example1_info']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3d500d60-4250-438f-a714-43a388acf53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dataTables_info</value>
      <webElementGuid>23b7b26e-9d4c-49b5-ad4b-44c89721174d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>example1_info</value>
      <webElementGuid>419cd1f3-9756-40f0-a4fc-261de447bfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>d9da1326-8ee8-44b7-bf43-1767c7bcc430</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>a727d41c-a87f-4877-99d6-5f3fc3ca727d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Showing 1 to 10 of 11 entries</value>
      <webElementGuid>ce3d1be9-0586-4d59-9e01-56f064e9d8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1_info&quot;)</value>
      <webElementGuid>b01756c1-437e-4ddd-8c75-c67948cdcde4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='example1_info']</value>
      <webElementGuid>0139375a-8e12-4f98-ab00-419dd648031b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='example1_wrapper']/div[3]/div/div</value>
      <webElementGuid>575e787a-39d1-40c7-8edc-0f8ca0813d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pakem, Kabupaten Sleman'])[2]/following::div[3]</value>
      <webElementGuid>3c7e3003-4e32-4093-b347-29d284895727</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guguk Panjang (Guguak Panjang), Kota Bukittinggi'])[1]/following::div[3]</value>
      <webElementGuid>b1c29a20-5d97-4a73-bfa6-d9e5144acc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marketplace PRO'])[1]/preceding::div[4]</value>
      <webElementGuid>a052bac2-45ef-405d-b0ce-6dd2d29ab0b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Showing 1 to 10 of 11 entries']/parent::*</value>
      <webElementGuid>92c0d2ba-4153-4bc5-a0d6-de1966a4f3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div</value>
      <webElementGuid>cc6b7d1b-700e-4b9b-bb92-870672fb3048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'example1_info' and (text() = 'Showing 1 to 10 of 11 entries' or . = 'Showing 1 to 10 of 11 entries')]</value>
      <webElementGuid>1987b14b-dcca-4a17-90af-47785dd09904</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
