<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilihan_Konfirmasi_status</name>
   <tag></tag>
   <elementGuidId>e4fe55a0-0578-4c00-a23b-91941be2cd70</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Konfirmasi?')&quot;])[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.open > ul.dropdown-menu > li:nth-of-type(3) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dab88811-6062-4ade-bcec-2bf5d25ecf33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin Ubah status pesanan jadi Konfirmasi?')</value>
      <webElementGuid>02f6ad1e-3a73-42b4-919c-93d7a4b1eb3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=2</value>
      <webElementGuid>1599de90-7a4f-4c08-89ea-e1afcd12b583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Konfirmasi</value>
      <webElementGuid>0a5da6f4-c49e-4102-ace2-d2212b48323c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[3]/a[1]</value>
      <webElementGuid>b2f17cd7-d246-4696-b5f1-394e9189562d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Konfirmasi?')&quot;])[6]</value>
      <webElementGuid>f777009c-b61d-4fe1-a19a-e32efa8085a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[6]/td[8]/center/div/ul/li[3]/a</value>
      <webElementGuid>cb56ccb4-1921-4eab-ada8-0747d324a262</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Konfirmasi')])[6]</value>
      <webElementGuid>ff817afe-5cf7-474b-866c-3385368a9392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[6]/following::a[1]</value>
      <webElementGuid>e483cf7f-fcf8-4719-bf3e-2180651796c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pending'])[8]/following::a[2]</value>
      <webElementGuid>ca602619-6e8b-41fe-b611-8fb880842224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dikirim'])[6]/preceding::a[1]</value>
      <webElementGuid>aa1ec2ca-8c77-43bd-aa52-7b062b21a10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[6]/preceding::a[2]</value>
      <webElementGuid>001e5a4a-5cc7-4b2d-850c-f8b3ad3a11ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=2')]</value>
      <webElementGuid>824cdee3-2650-468f-8b38-606217e1d236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[8]/center/div/ul/li[3]/a</value>
      <webElementGuid>a2240fbc-2b52-4b08-8511-8f2b9b96380d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=2' and (text() = 'Konfirmasi' or . = 'Konfirmasi')]</value>
      <webElementGuid>87e5e49b-60e8-4a56-ad95-814ba80ed31c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
