<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>status_pesanan_Dikirim</name>
   <tag></tag>
   <elementGuidId>163b13eb-a4d8-4b78-8670-940effe5f234</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Dikirim?')&quot;])[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.open > ul.dropdown-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5a8d7567-ba79-4ed1-a2bc-db55606f0c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin Ubah status pesanan jadi Dikirim?')</value>
      <webElementGuid>ee301c59-9fc3-49c0-90a3-34bce8a6839a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=3</value>
      <webElementGuid>27f9b10b-ca30-4ffe-907a-607b23d37780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dikirim</value>
      <webElementGuid>cd692122-b554-4372-94f2-b1a71098b15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>81d53a40-f9b5-415e-b661-0c1eee919060</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Dikirim?')&quot;])[7]</value>
      <webElementGuid>0da11af1-bd21-4a9a-8776-cfd2643c43d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[7]/td[8]/center/div/ul/li[4]/a</value>
      <webElementGuid>3cde77ce-42ed-4aeb-bd0b-921a4b0f8a7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dikirim')])[7]</value>
      <webElementGuid>c768f121-49b5-4637-9096-2413b2d724ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[11]/following::a[1]</value>
      <webElementGuid>9e74be50-cb34-4c95-abfc-157d289ecbb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[7]/following::a[2]</value>
      <webElementGuid>ee5e8328-40ff-480d-a5fc-704d1f053db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[7]/preceding::a[1]</value>
      <webElementGuid>e059ae1c-ec89-4421-bca6-8b169d31feda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal/Refund'])[4]/preceding::a[2]</value>
      <webElementGuid>9ecd6c5a-6b50-4284-8a37-beccb198fff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=3')]</value>
      <webElementGuid>84de25fa-d721-4004-bb3c-863c1ca881bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[8]/center/div/ul/li[4]/a</value>
      <webElementGuid>0f9268fa-8e2e-473e-84b5-920f6e2514b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=120&amp;status=3' and (text() = 'Dikirim' or . = 'Dikirim')]</value>
      <webElementGuid>39543942-7fdf-4a18-8d63-f0e50499aad6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
