<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Posisi_Kec</name>
   <tag></tag>
   <elementGuidId>12d6642d-13ad-4200-8f98-7cc01e2a01dc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_kecamatan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;list_kecamatan&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05326a95-2e7f-4342-b806-a36f1456e6af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>03ac0c9b-cc87-486d-b611-9351945f65d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kecamatan_id</value>
      <webElementGuid>24d96ecd-f9ca-49d6-bab1-368e9e84e9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kecamatan</value>
      <webElementGuid>38fdb8e6-4423-4245-9824-419b48cf98dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        - Pilih Kecamatan -
                      </value>
      <webElementGuid>9798cd8d-3846-49f5-a87e-611600794878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kecamatan&quot;)</value>
      <webElementGuid>d6ff91c5-be8d-464e-8975-134e537e9739</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kecamatan']</value>
      <webElementGuid>f8553b08-b4e9-4088-a803-7a00893296eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi'])[1]/following::select[3]</value>
      <webElementGuid>63df78ad-89dd-4749-8e91-fd4f853fd0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kendaraan'])[1]/following::select[4]</value>
      <webElementGuid>5c9fc3fa-7b99-4b31-8df7-64f724afbed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan'])[1]/preceding::select[1]</value>
      <webElementGuid>d5bc1d27-878d-49ee-9f52-11149d9d265e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongkir (Rp)'])[1]/preceding::select[4]</value>
      <webElementGuid>5730603e-7f40-46e8-aee5-47668fc99cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>e8e4b32f-5350-4c95-a640-3eb53a285587</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kecamatan_id' and @id = 'list_kecamatan' and (text() = '
                        - Pilih Kecamatan -
                      ' or . = '
                        - Pilih Kecamatan -
                      ')]</value>
      <webElementGuid>ff3874b8-d9c3-4235-bb38-c5dc5ac7524d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
