<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit_Tujuan_Kab</name>
   <tag></tag>
   <elementGuidId>45b518e9-6f17-4b9f-83cd-d0ff5cd28319</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#list_kotakabt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='list_kotakabt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>71b2ced5-5a42-481f-bc9e-a25bd8d028de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-mini</value>
      <webElementGuid>df68261a-e0dd-4207-a623-30229ab17ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>kota_idt</value>
      <webElementGuid>1f29fb00-aef3-40eb-91c3-404e74a8ba5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>list_kotakabt</value>
      <webElementGuid>d6c17f40-3e5b-4a62-8591-c65f78661068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                      - Pilih Kota / Kabupaten -
                      </value>
      <webElementGuid>7b90ce50-c79a-444b-928a-cb5faf2e52bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;list_kotakabt&quot;)</value>
      <webElementGuid>64fe3ccd-1eee-4b7c-9fc3-217efd5294a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='list_kotakabt']</value>
      <webElementGuid>1186bab7-f046-4c42-92f1-f23d337c08d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tujuan'])[1]/following::select[2]</value>
      <webElementGuid>bfdd89c0-ff2d-4dc7-a6a0-1c41039552d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Posisi'])[1]/following::select[5]</value>
      <webElementGuid>9f7f4b3e-a7e4-43f7-bbd9-9e61462d97e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ongkir (Rp)'])[1]/preceding::select[2]</value>
      <webElementGuid>ad5ac3c1-d38a-4d22-af95-4bc91262590a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keterangan'])[1]/preceding::select[2]</value>
      <webElementGuid>d8e2d922-53f7-4eba-994b-9409bb37421e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/select[2]</value>
      <webElementGuid>7bfec3b0-e326-484d-8460-cf3d5f36538c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'kota_idt' and @id = 'list_kotakabt' and (text() = '
                      - Pilih Kota / Kabupaten -
                      ' or . = '
                      - Pilih Kota / Kabupaten -
                      ')]</value>
      <webElementGuid>a7d02c7c-1aec-4c90-ad3b-5f73eb64b596</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
