<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data List Name_2</name>
   <tag></tag>
   <elementGuidId>c202ddf3-060d-430d-b7ee-bebbe5c1583a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.last-name</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table2']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ab483f76-7d5e-48da-a153-54767cf9154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>last-name</value>
      <webElementGuid>2d95f150-b79f-4b56-94b9-cf0526a1ad0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Smith</value>
      <webElementGuid>117208e2-bbe3-4854-96a6-8814ddf80cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table2&quot;)/tbody[1]/tr[1]/td[@class=&quot;last-name&quot;]</value>
      <webElementGuid>29885160-af43-4e89-b393-320a77685e99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table2']/tbody/tr/td</value>
      <webElementGuid>5be929e2-17f7-4672-a233-563203f21dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[2]/following::td[1]</value>
      <webElementGuid>2d63c1ca-1b60-44eb-86af-74b024caa95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Site'])[2]/following::td[1]</value>
      <webElementGuid>c1be20d3-d38b-4e55-bf8b-15fc1a82cb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='John'])[2]/preceding::td[1]</value>
      <webElementGuid>72b2b0b2-0aca-4753-aac2-a6b1966199f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='jsmith@gmail.com'])[2]/preceding::td[2]</value>
      <webElementGuid>8eef2d62-8601-4ecc-a663-bd7b8958c7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>75d17ff4-2080-4b18-8623-fe9c0b6fb770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Smith' or . = 'Smith')]</value>
      <webElementGuid>d26d31cf-d82f-4422-8337-c476e8e35fa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
