<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Data List Name_1</name>
   <tag></tag>
   <elementGuidId>5bec5092-f6a9-43dd-96a8-cde7392b9624</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table1']/tbody/tr/td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4e824490-a9c8-4da5-b05c-bf7da99e0efa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bach</value>
      <webElementGuid>2184c1d5-f3f6-4c2a-9bea-d922f56ea7a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table1&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>b41fd8dd-88c1-49cf-93cb-3f27a783f9a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table1']/tbody/tr/td</value>
      <webElementGuid>1a99aece-fd50-4a59-a526-b7152e7b7acb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[1]</value>
      <webElementGuid>ad599a90-b29c-4ebf-852e-8ca3289a8339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Web Site'])[1]/following::td[1]</value>
      <webElementGuid>b2dd68bf-d1a4-4226-89eb-0b6ae6f656e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Frank'])[1]/preceding::td[1]</value>
      <webElementGuid>82c0d708-45c3-4ad9-8c26-68c04fa77de3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fbach@yahoo.com'])[1]/preceding::td[2]</value>
      <webElementGuid>40e722cb-88ff-4a19-b8a5-408641315871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bach']/parent::*</value>
      <webElementGuid>4ccfd812-4b5d-4cdf-a324-55ba20d92e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td</value>
      <webElementGuid>85cbe395-56c5-43ea-ada3-b3c17e209280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Bach' or . = 'Bach')]</value>
      <webElementGuid>f1d53d99-fc38-41a0-bb5b-3864479eb1e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
