<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Last Name_2</name>
   <tag></tag>
   <elementGuidId>4c8fd848-b430-4828-b379-eafa50f53316</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#table2 > thead > tr > th.header</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='table2']/thead/tr/th[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>62defe61-4e9e-453c-91c8-727f3f20b82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>header</value>
      <webElementGuid>f858b201-e4c5-4db7-9a76-4acfdb5be561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Last Name</value>
      <webElementGuid>255a9e27-5a18-4f4d-a414-b0f034357245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;table2&quot;)/thead[1]/tr[1]/th[@class=&quot;header&quot;]</value>
      <webElementGuid>acbb3550-c378-4c86-b344-9994ab054ea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='table2']/thead/tr/th</value>
      <webElementGuid>71b29a4d-78dc-41dc-aa4d-962d8747f354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Example 2'])[1]/following::th[1]</value>
      <webElementGuid>09f0521e-f168-4106-8837-c0ecd418ec93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='delete'])[4]/following::th[1]</value>
      <webElementGuid>fa2a5a96-2dd1-4189-8840-b02ec34b7633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First Name'])[2]/preceding::th[1]</value>
      <webElementGuid>0e6a8d8a-5264-4bb9-8e81-acb34a0e694d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/thead/tr/th</value>
      <webElementGuid>a9942b03-dccb-40ab-8957-ec854bf2c7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[(text() = 'Last Name' or . = 'Last Name')]</value>
      <webElementGuid>2ec39d3f-5bde-4488-8487-6eb57cda11b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
