<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Kolom_Keterangan</name>
   <tag></tag>
   <elementGuidId>77a25ef9-257f-4cb3-b5ed-95116498c0d3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;example1&quot;]/tbody/tr/td[6]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(6)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3a66b7d0-dee2-4a68-bab6-aa68d2f82bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12 Menit</value>
      <webElementGuid>db181cd4-978b-4c41-99bb-c6cc5c302e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[6]</value>
      <webElementGuid>fcefc10e-4427-489f-8833-f729875e3a0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[6]</value>
      <webElementGuid>db8c74b3-a459-4da6-b613-0ade5c5dd9c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aur Birugo Tigo Baleh, Kota Bukittinggi'])[1]/following::td[2]</value>
      <webElementGuid>0be45ad3-d35d-44bd-b6d4-119c562dc606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guguk Panjang (Guguak Panjang), Kota Bukittinggi'])[1]/following::td[3]</value>
      <webElementGuid>ca69cac5-ad18-4e1b-93e0-ea8c36ca891c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roda 2'])[2]/preceding::td[3]</value>
      <webElementGuid>1f941128-50af-4a48-a548-2dfe993b1507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mandiangin Koto Selayan, Kota Bukittinggi'])[1]/preceding::td[4]</value>
      <webElementGuid>63064f5b-d2cb-4940-bd8f-2e6d00d68049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='12 Menit']/parent::*</value>
      <webElementGuid>1c558c49-50cd-4fda-97e2-71ad59a651f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]</value>
      <webElementGuid>521d749b-b18a-4e83-86d1-32821665765b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '12 Menit' or . = '12 Menit')]</value>
      <webElementGuid>85071a67-c012-469e-bb34-564d37ba21bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
