<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_IconImage</name>
   <tag></tag>
   <elementGuidId>4c754a0f-45d5-4f37-8f65-fc791c9baf8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='example1']/tbody/tr/td[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td:nth-of-type(7)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5279d7cc-e524-43dc-a70c-b046a49c5792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>anyaforger20.png</value>
      <webElementGuid>3ad2e565-61a7-43cd-a697-7ca7f8ae8753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;odd&quot;]/td[7]</value>
      <webElementGuid>72e5034c-22db-4bc8-b986-e8a5c6f44f08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr/td[7]</value>
      <webElementGuid>506cc760-4352-473f-a487-9f002b35db9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ASD123'])[1]/following::td[1]</value>
      <webElementGuid>374e8453-e2bb-4ac9-9e62-b79064d7a205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 25,000'])[1]/following::td[3]</value>
      <webElementGuid>34fc3ad9-eeef-4069-943b-a630bb1cc0da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Star Seller 5 Bulan'])[2]/preceding::td[3]</value>
      <webElementGuid>180fae68-d3f9-4af6-98e9-914e743e469c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rp 25,000'])[2]/preceding::td[5]</value>
      <webElementGuid>0e674763-e31c-4dbd-902f-c507f5109543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='anyaforger20.png']/parent::*</value>
      <webElementGuid>0a96b87b-7121-44a6-b7ac-11f29d1de675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>b2e2cc70-66bd-477d-bca4-c45d5444f743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'anyaforger20.png' or . = 'anyaforger20.png')]</value>
      <webElementGuid>c1d7543f-4e45-4e8b-9e20-fc9048a6c065</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
