<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_homepage</name>
   <tag></tag>
   <elementGuidId>3b8939eb-188d-4d32-86ba-c6c6d455892e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[contains(@src,'https://10.9.2.63/ecommerce/asset/logo/tajalapak-black.png')])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.navigation__left > a.ps-logo > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c9bba2ac-e4b2-4e34-9884-2e5231dab71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/asset/logo/tajalapak-black.png</value>
      <webElementGuid>238fa293-bdea-4fbe-8394-d07fefab8e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;loaded&quot;]/header[@class=&quot;header header--mobile&quot;]/div[@class=&quot;navigation--mobile&quot;]/div[@class=&quot;navigation__left&quot;]/a[@class=&quot;ps-logo&quot;]/img[1]</value>
      <webElementGuid>62f82c30-178a-4ec1-b4ce-a7c391bd36d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[contains(@src,'https://10.9.2.63/ecommerce/asset/logo/tajalapak-black.png')])[2]</value>
      <webElementGuid>baa09613-5a31-4666-a95a-5db831fe90d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header[2]/div/div/a/img</value>
      <webElementGuid>d9dd366f-626d-4bc6-9820-cc9cea6a261c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://10.9.2.63/ecommerce/asset/logo/tajalapak-black.png']</value>
      <webElementGuid>145fc107-d0c9-4ebe-ac5e-ffc3b3198d21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
