<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Dikirim</name>
   <tag></tag>
   <elementGuidId>c0501bb2-1fd3-4827-8f00-c9bf0bb4b3aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;example1&quot;]/tbody/tr[1]/td[8]/center/div/ul/li[4]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.btn-group.open > ul.dropdown-menu > li:nth-of-type(4) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d832cbc9-27c0-4bed-bae3-f49886d48d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>return confirm('Yakin Ubah status pesanan jadi Dikirim?')</value>
      <webElementGuid>9398e522-edcd-4540-8176-3f88dd72ae35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=316&amp;status=3</value>
      <webElementGuid>d25f1a36-a5a4-4224-8e0e-7b5bdfc9e825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dikirim</value>
      <webElementGuid>0323da73-ac3a-4638-a3fa-9f91b3f64102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;example1&quot;)/tbody[1]/tr[@class=&quot;even&quot;]/td[8]/center[1]/div[@class=&quot;btn-group open&quot;]/ul[@class=&quot;dropdown-menu&quot;]/li[4]/a[1]</value>
      <webElementGuid>5342f40d-b3d2-4e03-b0ed-73cb29df6401</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick=&quot;return confirm('Yakin Ubah status pesanan jadi Dikirim?')&quot;])[2]</value>
      <webElementGuid>e54b88c9-28e6-4603-b029-f7a865c0281c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='example1']/tbody/tr[2]/td[8]/center/div/ul/li[4]/a</value>
      <webElementGuid>c409a526-b65f-41d5-ab9e-9b188dec54da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Dikirim')])[2]</value>
      <webElementGuid>1bcf85e5-9415-49d0-9fac-8d62565ec80b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Konfirmasi'])[4]/following::a[1]</value>
      <webElementGuid>1a0a2eb1-556f-4149-bb1f-ef351f864c40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proses'])[2]/following::a[2]</value>
      <webElementGuid>77347019-194c-49db-97d7-ce3779dde4fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selesai'])[2]/preceding::a[1]</value>
      <webElementGuid>121d5894-0856-40fa-a5b8-4a3def3791f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Batal/Refund'])[1]/preceding::a[2]</value>
      <webElementGuid>cd0acd6e-1a70-4112-adcc-68ac4ce0995d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=316&amp;status=3')]</value>
      <webElementGuid>35bc3d50-0964-4508-929f-548906976f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[8]/center/div/ul/li[4]/a</value>
      <webElementGuid>0ee21181-69f4-40e2-86f2-def53d594326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/administrator/penjualan_konsumen?id=316&amp;status=3' and (text() = 'Dikirim' or . = 'Dikirim')]</value>
      <webElementGuid>6634add6-4294-4003-b467-d7e1dc1b64d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
