<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Syarii Sentral Java</name>
   <tag></tag>
   <elementGuidId>69cab077-38a5-4c3e-8947-4d549103b6a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='tab-1']/div/div/div/div/div[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.ps-product__vendor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c546ddd8-d564-4234-b85e-8504e40c30a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ps-product__vendor</value>
      <webElementGuid>f63a6cba-9f80-4d32-ae67-b30aacc9f179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://10.9.2.63/ecommerce/u/syarii-sentral-java</value>
      <webElementGuid>1b995f1d-951b-44ee-84ec-022821e881cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Syarii Sentral Java</value>
      <webElementGuid>e1bff28c-1aa7-4dc6-929b-5f77a0a0664b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-1&quot;)/div[@class=&quot;ps-shopping-product&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xl-3 col-lg-4 col-md-4 col-sm-6 col-6&quot;]/div[@class=&quot;ps-product&quot;]/div[@class=&quot;ps-product__container&quot;]/a[@class=&quot;ps-product__vendor&quot;]</value>
      <webElementGuid>2e9961d3-eedd-499e-86d6-be3bc01257a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-1']/div/div/div/div/div[2]/a</value>
      <webElementGuid>807fc6a0-ff60-4475-a3f6-4a0576359d11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Syarii Sentral Java')]</value>
      <webElementGuid>9f69b1a2-450e-4782-b07b-9315a6acd07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(11)'])[2]/following::a[7]</value>
      <webElementGuid>c59dff29-ff81-4eb7-92de-f743db367b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pashmina Instan Rafella - RLN1.1 Sweet,..'])[1]/preceding::a[1]</value>
      <webElementGuid>bd96e8fd-d380-4347-992b-88693d9d0d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pashmina Instan Rafella - RLN1.1 Sweet,..'])[2]/preceding::a[2]</value>
      <webElementGuid>ecf1365e-265c-4e66-9764-ed34fca1326d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Syarii Sentral Java']/parent::*</value>
      <webElementGuid>9d16eadb-8af1-4a81-8003-cf2550d2b9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://10.9.2.63/ecommerce/u/syarii-sentral-java')]</value>
      <webElementGuid>f44ad9c5-24b5-47a1-913c-73b8f140684c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div/div[2]/a</value>
      <webElementGuid>20676dad-1b2e-4ce4-9a00-f708fc76ea47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://10.9.2.63/ecommerce/u/syarii-sentral-java' and (text() = ' Syarii Sentral Java' or . = ' Syarii Sentral Java')]</value>
      <webElementGuid>46ee3561-c5ca-462a-894a-72dae2ff765e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
