<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>harga_produk_keranjang</name>
   <tag></tag>
   <elementGuidId>09c07e41-0f25-4eed-8a1d-af9315429e08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[10]/div/div/div/div/div/div[1]/form/div[1]/div/div[2]/p[2]/small/b</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
