<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_metode_pembayaran</name>
   <tag></tag>
   <elementGuidId>8c77b177-0ff3-48a4-938e-6620fb51afa9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='saldo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#saldo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e489463-2231-434f-a7a8-2a4f07d38987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>deb0d88b-4dd0-466f-85de-6058de7dc548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>metode</value>
      <webElementGuid>a3bfa5ab-9ff7-40bb-a04d-9e6b5e1a245c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>0963be20-02f3-4f14-b3c2-5cf5c5cd8de3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>saldo</value>
      <webElementGuid>cff80824-e505-4e0b-8de4-287ce17500b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;saldo&quot;)</value>
      <webElementGuid>4c9fde73-9b84-4a7b-b5af-bc039cbf9972</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='saldo']</value>
      <webElementGuid>96a2c4a0-8020-4034-a3da-17888b38788a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input[2]</value>
      <webElementGuid>2dacbe64-75ef-4117-8739-7666b2cd8c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'metode' and @id = 'saldo']</value>
      <webElementGuid>a9549084-b5cd-4237-b2b8-f18e7b2087c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
