<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>pilihan_kurir</name>
   <tag></tag>
   <elementGuidId>eea54830-7854-4051-a6f4-49fde87873d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='serv-99-2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#serv-99-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>fd5a9452-6410-4eff-b7f9-b4c773a68777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>serv-99-2</value>
      <webElementGuid>a229f86f-5007-461f-99cb-db42198f2392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>klikongkir10('2','SOPIR','12000','12,000',this.id)</value>
      <webElementGuid>7335151d-9505-4f1c-8158-2cef247328eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-group-item clearall-kurir selected-ongkir10</value>
      <webElementGuid>5d7b5ce3-c613-43e7-ac81-0f087dc273ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vixion R (BA 4665 LN) Rp. 12,000 / 2 hari</value>
      <webElementGuid>069502fa-4f2f-4bfa-adcb-32f8fd9335b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;serv-99-2&quot;)</value>
      <webElementGuid>d006718b-9a0b-4ac6-89b0-b76212bd7000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='serv-99-2']</value>
      <webElementGuid>8f72fd85-4416-45e6-be16-4bd9e76f872b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list_sopir_div1']/li</value>
      <webElementGuid>32d06ec9-4ab3-4216-8fe8-9caf5cd90997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kirim via COD (Bayar Di tempat)'])[1]/following::li[1]</value>
      <webElementGuid>cb66fd2a-cfc0-45f2-b537-aa6a3d7e70ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Syarii Sentral Java'])[2]/following::li[1]</value>
      <webElementGuid>09cb6313-3d9c-463d-9989-4dc9235d9019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li</value>
      <webElementGuid>91ed9046-f6e0-45a2-a87a-06331af5850b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'serv-99-2' and (text() = 'Vixion R (BA 4665 LN) Rp. 12,000 / 2 hari' or . = 'Vixion R (BA 4665 LN) Rp. 12,000 / 2 hari')]</value>
      <webElementGuid>06a863f6-76a2-4f45-9075-996da235eb05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
